# Generated by Django 5.1.1 on 2024-09-10 19:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_alter_course_access"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, null=True, verbose_name="image"
            ),
        ),
    ]
