# Generated by Django 5.1.1 on 2024-09-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_lesson_thumbnail_lesson_video"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="lesson",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
