# Generated by Django 5.1.1 on 2024-09-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0007_alter_lesson_options_lesson_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
