# Generated by Django 5.1.1 on 2024-09-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0011_lesson_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="public_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=130, null=True
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="public_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=130, null=True
            ),
        ),
    ]
